### ISSUE TITLE
Restrict user to access kibana console with only view access.

### ISSUE THREAD

**Issue by himmatb** [openshift/origin-aggregated-logging#1113]
Is there any way available to restrict specific user can only view particular index on Kibana and other admin user can view and edit anything index.

I have done one workaround like added user to view role for that particular project, but in this case user is able to view and edit only that particular projects logs and other setting means that guy is admin of that project. 

Please help me with awesome solution!! Any leads help me will be appreciated!! :

**Comment by jcantrill** [comment]
That is the point of the multi-tenant plugin to Elasticsearch.  Individual users are restricted to indices that match the projects for which they are able to see.  Any permissions outside of what Openshift offers would require you to manually edit the permissions documents  to specify indices for a given user.  This  will require you to pull the SearchGuard documents out of the image, mount them into a configmap or secret, and update them accordingly.  Additionally, because authentication and authorization relies on Openshift Oauth, each user will need an identity that can be validated by Openshift.

**Comment by himmatb** [comment]
I got your point.. So i need to modify searchguard document based on user permissions.. But can you please help mewith steps
require me to pull the SearchGuard documents out of the image, mount them into a configmap or secret, and update them accordingly. If possible..

**Comment by richm** [comment]
take a look at https://github.com/openshift/origin-aggregated-logging/blob/b5db42310bd620180397ba9fbc2297b3259a4624/hack/enable-kibana-msearch-access.sh for an example of how to change searchguard acl configuration at runtime
