### ISSUE TITLE
External VM logs logged into project.mux-undefined.xxxx index, how to store application logs to specific index

### ISSUE THREAD

**Issue by himmatb** [openshift/origin-aggregated-logging#1144]
I have enabled mux as an aggregator in our logging stack configuration on production setup..
I have created multiple namespace to segregate logs are coming from different different extenal vm application's and stores in respective namespace index .

Currently all logs which i am forwarding to aggregator from external VM are by default logged in to project.mux-undefined.xxxxx index.
how can i forward logs to aggregator which can be stores logs to application specific diffrent index?

Please help me with solution.

**Comment by richm** [comment]
If you are using mux, first read https://github.com/openshift/origin-aggregated-logging/blob/master/docs/mux-logging-service.md - specifically - https://github.com/openshift/origin-aggregated-logging/blob/master/docs/mux-logging-service.md#tag

**Comment by himmatb** [comment]
it means if i will not tag to logs then its automatically goes to project.mux-undefined.xxxxx index.
i have created other namespace like below but dont know how logs will use this index using ansible inventory:

openshift_logging_mux_namespaces=["externalvmlogs"]

Please confirm whether below tag mention is correct or wrong:
<source>
  @type tail
    path /opt/app/fluentd_links/*.log
  pos_file /var/fluentd/fluentd.log.pos # This is where you record file position
  tag project.externalvmlogs.*
  read_from_head true
  <parse>
    @type multiline_grok
multiline_start_regexp /^\[/
<grok>
....
.....
...
If you have any sample fluentd configuration which is sends logs to specific namespace tag .. that will really help me..


Thanks in advance..

**Comment by richm** [comment]
> this means if i didnt tag but its automatically goes to project.mux-undefined.xxxxx index.

if mux can't figure out which namespace to use for your logs, it will put them in project.mux-undefined.xxxxx or .orphaned.YYYY.MM.DD

> I have created other namespace like below but dont know how logs will use this index using ansible inventory

Right.  That just adds the namespace to openshift.  You are still responsible for tagging or otherwise annotating your log records that you send to mux with that namespace.

It looks like your tagging is correct:

tag project.externalvmlogs.*

The next step would be to add some sections like this:
```
<filter project.externalvmlogs.**>
  @type stdout
</filter>
```
in your mux fluent.conf in the configmap to print out the logs to see what is happening to them.
