### ISSUE TITLE
Modifying Delayed Allocation Setting

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#1467]
While monitoring and maintaining the operations clusters, we routinely need to perform rolling restarts and run into issues with unassigned shards which are reported like:
```
project.foo.abc-123.2018.11.1              0     r  UNASSIGNED    NODE_LEFT
```
Many times after the nodes return I see the cluster stuck in yellow state because the unassigned shards never become allocated.  The [reroute](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cluster-reroute.html#_retry_failed_shards) documentation alludes to an allocation retry count which makes me wonder if the cluster gives up.

There additionally is documentation about [delayed allocation](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/delayed-allocation.html) which I think we should consider bumping the default (i.e. 1m) to at least something like 5 minutes. It's not uncommon for a pod to take that long to terminate and scale back up.  What concerns might we have or drawbacks to modifying this setting?

Also found [this](https://github.com/elastic/elasticsearch/pull/15912/files#diff-5f7818b093901b6114a63793bc045f03R93) which provides some additional info but still is a little lacking IMO.

**Comment by portante** [comment]
Seems worth to bump the timeout to even as high as 10 minutes or more.  The down side to the high delay seems to be when one removes a node permanently, which as the documentation notes, an operator pattern can change the setting for `node_left` delayed allocation in order to direct ES to start reallocating if necessary.

Overall, seems like a win.

**Comment by lukas-vlcek** [comment]
@jcantrill To be honest the documentation is not crystal clear to me. Do you say that if we have cluster with 2 nodes and one index `X` with 1 shard and 1 replica, then we should see one node holding primary, second holding replica. Like this:

| Node 1 | Node 2 |
|---|---|
| `Shard X (primary)` | `Shard X (replica)` |

Now, if we bring down the node holding replica and wait for specified amount of time (we can tail log of the first node to see the message about giving up the allocation of replica shard as the documentation suggests) then if we start the second node again it will never allocate the replica?

| Node 1 | Node 2 |
|---|---|
| `Shard X (primary)` |  |

`Shard X (replica)` is `UNASSIGNED` due to  `NODE_LEFT`?

This sounds odd to me. However, if this is the case it should be easy to simulate and verify locally.

**Comment by jcantrill** [comment]
@lukas-vlcek I can not positively confirm the behavior you describe as there is a large 'shotgun' approach I am taking trying to get multiple clusters functional all at once.  I do know, however, that I recently was working on a cluster where their were unassigned replica shards because of 'NODE_LEFT' which were never being assigned until I explicitly rerouted them.  It baffles me why ES would give up given the node did come back online but it also took longer then 1m, which I assume is the default we have.  These clusters in particular I am still struggling to get them to cluster in a timely manor and kibana keeps getting gateway timeouts.

**Comment by lukas-vlcek** [comment]
How about increasing `index.allocation.max_retries` instead in elasticsearch.yml? (it is `5` by default)

So instead of increasing the delayed allocation timeout from `1m` to say `5m` we can keep it intact (without worrying to update it from operator, i.e. without making the ES cluster configuration more state-full) and just increase the `index.allocation.max_retries` to `10`. Wouldn't it have the same impact in the context of this particular use case?

Still, I would like to get to the root case here. We seem to be just working around symptoms.

**Comment by jcantrill** [comment]
@lukas-vlcek I agree we dont know the root cause and I think modifying either setting moves us closer to a better outcome, just from a different angle. IMO, I think  the platform should allow us to scale down and up an ES node in less then 5 minutes; this doesn't seem unreasonable.

**Comment by portante** [comment]
@lukas-vlcek, how will raising the delayed allocation timeout increase the time it takes to go green?  Won't it only increase the time to go green if the pod cannot be restarted before the time it would take to replicate all the data?

If we know that a pod is going to rejoin the cluster, why would we copy all that data to one of the nodes, only to copy it back to the 3rd node that is rejoining imminently?

When you have lots of data, where ES limits the number of concurrent shard recoveries and bandwidth of recovery (last I checked), won't the time to go green likely be much longer than a pod restart?

Finding out why pod restarts take so long is one thing to investigate.  But raising the time out, to 10m or even 30m, seems like a reasonable win to avoid all the data copies.  Raising the retries to a very large number is also worth considering, but as the documentation [1] states, using the `_reroute?retry_failed` API can be issued to later when the node comes back as well (the ES operator could issue this).

Thoughts?

[1] https://www.elastic.co/guide/en/elasticsearch/reference/5.3/cluster-reroute.html#_retry_failed_shards

**Comment by jcantrill** [comment]
> However, what still bothers me is if increasing the delay timeout can really help with the symptoms @jcantrill described above. I draw some node restart scenarios on the whiteboard and I still can not see how we can end up with unassigned shard (due to `NODE_LEFT`) after node restart unless the rolling over process is either wrong or poorly executed.
> 
Let me add the clusters which most recently prompted me to file this issue are experiencing problems with forming a cluster.  What is not known in the 5 attempts is how they are executed.  Is it sequentially?  Is there some sort of back-off algorithm that takes into account the max time?   What if while trying to form the cluster, we exceed the time (and presumably the attempts) and then the node comes back online.  The cluster is now formed but there is no logic to allocate the shards without admin intervention.  Add in the possibility the cluster is under resourced or that Openshift has decided to restart the pod because of a liveliness probe failure.

**Comment by lukas-vlcek** [comment]
@jcantrill @portante @wshearn If we follow [official rolling upgrade](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/rolling-upgrades.html) process then what we should see is the following:

  1. **Disable allocation**
   Notice this explicitly disables [delayed allocation](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/delayed-allocation.html) timeout which also means there should be no giving up shard allocation due to [retry failed](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cluster-reroute.html#_retry_failed_shards), are we on the same page here?
  2. Stop indexing (are we doing this by scaling fluentd or by other means?)
  3. Perform a single node upgrade (In our case we upgrade the image)
  4. Upgrade all plugins (We already do this as part of step 3. as everything is in the same image)
  5. Start the node and confirm it joins the cluster.
   So **we really wait** until the node joins, right? Notice the allocation is still disabled.
  6. **Reenable shard allocation**
   If I am not mistaken only from this point the delayed allocation is in effect again (including the retry failed).
  7. We **wait again** for the cluster to become green or simply "healthy enough"

If we are talking about extensive wait period in step 5 then I do not see how any changes to delayed allocation timeout should have any effect.

**Comment by jcantrill** [comment]
> @jcantrill @portante @wshearn If we follow [official rolling upgrade](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/rolling-upgrades.html) process then what we should see is the following:
> 
> 1. **Disable allocation**
>    Notice this explicitly disables [delayed allocation](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/delayed-allocation.html) timeout which also means there should be no giving up shard allocation due to [retry failed](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cluster-reroute.html#_retry_failed_shards), are we on the same page here?
> 2. Stop indexing (are we doing this by scaling fluentd or by other means?)

This step we do not do, we simply allow fluent to 'stop' by back pressure.

> 3. Perform a single node upgrade (In our case we upgrade the image)
> 4. Upgrade all plugins (We already do this as part of step 3. as everything is in the same image)
> 5. Start the node and confirm it joins the cluster.
>    So **we really wait** until the node joins, right? Notice the allocation is still disabled.
> 6. **Reenable shard allocation**
>    If I am not mistaken only from this point the delayed allocation is in effect again (including the retry failed).
> 7. We **wait again** for the cluster to become green or simply "healthy enough"
> 
> If we are talking about extensive wait period in step 5 then I do not see how any changes to delayed allocation timeout should have any effect.

**Comment by lukas-vlcek** [comment]
May be not stopping indexing can have its risks but I am not sure the symptoms would be the same as described above.

We should get and investigate logs. This would tell us a lot more. Without this what I can suggest right now is exposing more allocation and rebalance cluster settings as metrics via Prometheus plugin to enable tracking `cluster.routing.allocation.enabled`, `cluster.routing.rebelance.enabled` and the like...

This would allow us to make sure (or alert otherwise) that during rolling restarts the allocation stays disabled. 

See: https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/145
