### ISSUE TITLE
EFK upgrade to 3.11 failing

### ISSUE THREAD

**Issue by ayushmathur86** [openshift/origin-aggregated-logging#1498]
I'm trying to upgrade origin-aggregated-logging stack from 5.4.2 to 6.2.3 following the approach from tag 3.11 of logging project. 
The elasticsearch nodes are upgraded but the don't form a single cluster with 2 nodes, instead now I have 2 cluster with 1 node each.
Furthermore, they are not picking up custom configuration eventhough:  
`cp /usr/share/java/elasticsearch/config/* $ES_CONF` is present. 

On further analysis, I found that this command copies the symlink for elasticsearch.yml instead of actual file and this can't be read. Also, on using -H switch, it does copy the actual file, but xpack loading starts to fail with reason: 

> Permission denied on /tmp/ca-cert.crt

 which is CA certificate required for X-Pack.
Could you please provide me the steps to resolve the issue and create a single cluster with all nodes present.
 Please note we are using kubernetes plugin v6.2.3.1 for discovery and discovery.zen.hosts_provider: kubernetes is present in 

> custom config file which is located at /usr/share/elasticsearch/config

The POD logs from both nodes are attached for reference when symlink was being copied.
[logging-es-g7c8vog7-23-nhphr.log](https://github.com/openshift/origin-aggregated-logging/files/2795577/logging-es-g7c8vog7-23-nhphr.log)
[logging-es-nmvkfjuy-14-027gm.log](https://github.com/openshift/origin-aggregated-logging/files/2795578/logging-es-nmvkfjuy-14-027gm.log)

**Comment by richm** [comment]
> I'm trying to upgrade origin-aggregated-logging stack from 5.4.2 to 6.2.3 following the approach from tag 3.11 of logging project.

I don't know what this means.  the origin-aggregated-logging stack only supports Elasticsearch version 5.6.13

**Comment by jcantrill** [comment]
> I'm trying to upgrade origin-aggregated-logging stack from 5.4.2 to 6.2.3 following the approach from tag 3.11 of logging project.

This is not possible until the multi-tenant plugin is migrated.  I would expect ES to flat out reject the plugin because of the version.  Initial work is here: https://github.com/jcantrill/openshift-elasticsearch-plugin/tree/6.x  but last i made an effort it only compiled.  

> The elasticsearch nodes are upgraded but the don't form a single cluster with 2 nodes, instead now I have 2 cluster with 1 node each.

We would only ever recommend running either a simple 1 node or a 3 node cluster; never 2.

> Furthermore, they are not picking up custom configuration eventhough:
> `cp /usr/share/java/elasticsearch/config/* $ES_CONF` is present.
> 
> On further analysis, I found that this command copies the symlink for elasticsearch.yml instead of actual file and this can't be read. Also, on using -H switch, it does copy the actual file, but xpack loading starts to fail with reason:
This  setup is not designed to support XPack as we utilize SearchGuard.
> 
> > Permission denied on /tmp/ca-cert.crt
> 
> which is CA certificate required for X-Pack.
> Could you please provide me the steps to resolve the issue and create a single cluster with all nodes present.
> Please note we are using kubernetes plugin v6.2.3.1 for discovery and discovery.zen.hosts_provider: kubernetes is present in

We no longer rely on the kubernetes plugin for discovery as discovery can be accomplished by using a headless service.

> 
> > custom config file which is located at /usr/share/elasticsearch/config
> 

Closing this issue as it's obvious you are trying to highly customize the environment which is outside the scope or intention of where OKD cluster-logging is going.
