### ISSUE TITLE
Filter event with secure forwarder

### ISSUE THREAD

**Issue by nabbdl** [openshift/origin-aggregated-logging#1505]
We have configured the secure forwarder in order to have all the logging on a third party system (Splunk). The problem is that it fills up our system with unneeded logs. Is there a way to segregate/filter logs send to the secure forwarder based on index, namespace or whatever. The purpose here is to get only the applications log and ideally only the logs from dedicated namespaces.

**Comment by jcantrill** [comment]
If you have control of the instance receiver that receives logs from OKD fluent instance, why not filter the logs there? There currently no option to opt-in/opt-out of various namespaces from OKD logging.

**Comment by richm** [comment]
> If you have control of the instance receiver that receives logs from OKD fluent instance, why not filter the logs there? There currently no option to opt-in/opt-out of various namespaces from OKD logging.

You do, but 
- you have a lot of excess bandwidth to deal with
- you lose the tagging information - all of the tags are just `output_tag` so you have to do deep log inspection (i.e. more ram and cpu resources) in order to extract the `kubernetes.namespace_name` or `kubernetes.namespace_id` etc. from each record

**Comment by nabbdl** [comment]
Interesting one. I’ll test it. I’ve also find in the project below a way to filter on the secure forwarder which is also promising:
https://github.com/CDCgov/openshift-fluentd-forwarder
