### ISSUE TITLE
Add tuning knobs to ES

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#163]
e.g. http://evertrue.github.io/blog/2014/11/16/3-performance-tuning-tips-for-elasticsearch/
And any findings from the aos scalability team

**Comment by lukas-vlcek** [comment]
IMO rather than tuning isolated aspects we need to get view of broader family of metrics (including history), good starting point can be [10-elasticsearch-metrics-to-watch](https://www.oreilly.com/ideas/10-elasticsearch-metrics-to-watch) (though I would add more this this, like watching internal ES queues, especially the bulk request queue for logging use case).

**Comment by jcantrill** [comment]
tuning knobs would take the form of tweaks to openshift/cluster-logging-operator and openshift/elasticsearch-operator
