### ISSUE TITLE
How to Configure Fluentd to collect logs from non-cluster application to OKD 3.11 cluster

### ISSUE THREAD

**Issue by imranrazakhan** [openshift/origin-aggregated-logging#1810]
We have deployment of IOT based solution in which multiple application deployed on Openshift OKD 3.11, We are using Fluentd for central logging.

Our couple of applications are deployed outside of OKD cluster we want to use OKD Cluster Fluentd for those application.

Does OKD Fluentd provide such option or expose any route to receive logs from out of cluster? or any alternate suggestion?

**Comment by jcantrill** [comment]
> We have deployment of IOT based solution in which multiple application deployed on Openshift OKD 3.11, We are using Fluentd for central logging.
> 
> Our couple of applications are deployed outside of OKD cluster we want to use OKD Cluster Fluentd for those application.
> 
> Does OKD Fluentd provide such option or expose any route to receive logs from out of cluster? or any alternate suggestion?

OKD only uses fluentd as a collector to scrape container logs and ship them to storage;  OKD currently uses Elasticsearch.  There is no option to configure fluent to additionally receive logs.  Additionally, the Elasticsearch data model and cluster logging in general are not designed to be a general purpose logging solution.  The multi-tenancy features are highly coupled to OpenShift and which projects a user is capable of seeing.

You could expose a route to Elasticsearch in order to push logs, but this would require you to alter what CN and other ACL documents are utilized by Elasticsearch

**Comment by imranrazakhan** [comment]
@jcantrill fluentd has syslog plugin "https://docs.fluentd.org/input/syslog", Cant we add configuration and expose below port as service?

```
<source>
  @type syslog
  port 5140
  bind 0.0.0.0
  tag system
</source>
```

**Comment by jcantrill** [comment]
> @jcantrill fluentd has syslog plugin "https://docs.fluentd.org/input/syslog", Cant we add configuration and expose below port as service?
> 
The logging stack is designed for a very narrow set of usecases and, like any project, we are constrained by resources.  Adding the configuration is more then one file modification.  It requires:
* Justification by PM for the need
* Development work to scope the change
* QE Testing to ensure the change "works"
* Documentation of the "feature"

You are free to modify the configuration as you choose but that does not mean it is supported. 
> 
> In fluent.conf i saw entries of two configurations which are currently empty, so whats their intended purpose?
> 
Likely preparing for a future that never materialized.
