### ISSUE TITLE
authorization for kibana under OKD 4.x

### ISSUE THREAD

**Issue by aneagoe** [openshift/origin-aggregated-logging#2007]
I'm currently struggling to understand the way that authorization is managed and whether things can be tuned in OKD 4.x without breaking or having an unsupported logging stack deployment. Documentation is very scarce when it comes to the presentation layer and multi-tenancy, whether it's still using https://github.com/fabric8io/openshift-elasticsearch-plugin and so on are not very transparent.
Specifically, I'm trying to answer the following questions:

- how can we make certain visualizations or dashboards available to all users in the cluster (ie say for cluster-reader role)?
- is it possible to pre-create index patterns for users? we find it extremely difficult to explain to all our users they need to do this manually and furthermore, they have to be redone in case of a stack redeploy

**Comment by jcantrill** [comment]
> I'm currently struggling to understand the way that authorization is managed and whether things can be tuned in OKD 4.x without breaking or having an unsupported logging stack deployment. Documentation is very scarce when it comes to the presentation layer and multi-tenancy, whether it's still using https://github.com/fabric8io/openshift-elasticsearch-plugin and so on are not very transparent.

This depends what version of 4.x  you are referring.  The following links may provide you with the explanation:

* 4.4 or earlier: [openshift-elasticsearch-plugin](https://github.com/openshift/elasticsearch-operator/blob/master/docs/access-control.md)
* 4.5 and later: [openshift/elasticsearch-proxy](https://github.com/openshift/elasticsearch-operator/blob/master/docs/access-control.md)

> Specifically, I'm trying to answer the following questions:
> 
> * how can we make certain visualizations or dashboards available to all users in the cluster (ie say for cluster-reader role)?

Cluster admins have access to a common tenant that is shared with anyone in that role.  In addition, they have a private tenant like non-admin user's.  User's of a common tenant share all visualizations.  There is currently no way to define a set of user's who can share a common tenant.  I would encourage you to file an RFE at https://issues.redhat.com to explain your usecase.  Alternatively, you can go unmanaged and modify the permissions but those have not been extracted from the image so they will not survive restarts. 

> * is it possible to pre-create index patterns for users? 

Earlier versions of the stack precreated index-patterns because it was possible to do so in the plugin.  We investigated this possibility when moving the proxy and found technically challenges that made for a user experience that was not smooth.  We made the decision to document the procedure which amounts to three steps users do once.
> we find it extremely difficult to explain to all our users they need to do this manually and furthermore, they have to be redone in case of a stack redeploy

I would disagree with this statement and it is inaccurate. User's need to do this once when moving to 4.5 as the entire security plugin and tenant model has changed.  I have not seen any cases where user's need to "redo" these steps unless the stack is redeployed from scratch with new PVCs

**Comment by aneagoe** [comment]
Thanks for pointing out the elasticsearch-proxy. I'm using OKD 4.5 and a consequence of several minor updates was that a *new* stack was deployed which resulted in new PVCs. Not sure why that happened but looks similar to https://github.com/openshift/origin-aggregated-logging/issues/1963. I will pay close attention next time it happens after an upgrade and check the operator logs.
I'm not sure I can file an RFE since I'm using OKD and thus no redhat support. But I'm surprised this is not more common, I would imagine it useful for admins to present a cluster wide view of things (ie logged entries in past 24h, a pie-chart with top 10 namespaces that generate most logs, a top list of pods that generate most logs etc.).

**Comment by jcantrill** [comment]
> Thanks for pointing out the elasticsearch-proxy. I'm using OKD 4.5 and a consequence of several minor updates was that a _new_ stack was deployed which resulted in new PVCs. Not sure why that happened but looks similar to #1963. I will pay close attention next time it happens after an upgrade and check the operator logs.

There was a bug recently fixed related to ownerrefs being polluted which caused objects to be deleted.  This has since been fixed but is plaguing users in general

> I'm not sure I can file an RFE since I'm using OKD and thus no redhat support. But I'm surprised this is not more common, I would imagine it useful for admins to present a cluster wide view of things (ie logged entries in past 24h, a pie-chart with top 10 namespaces that generate most logs, a top list of pods that generate most logs etc.).

Anyone can file an RFE and it may make it into the RH product which means it would be here and available with OKD.  The issue of support is another matter
