### ISSUE TITLE
 Importing kibana dashboard by CLI  is needed in openshift EFK stack

### ISSUE THREAD

**Issue by lihongbj** [openshift/origin-aggregated-logging#2031]
I have installed EFK stack in openshift 4.5 for cluster logging, and a route named `kibana` is created and can be used to navigate to the kibana web UI, where my kibana dashboard can be imported **manually**. Meanwhile, in some cases, those kibana dashboards need to be imported **programingly/automatically via commandline** in k8s cluster env. 

When I tried to call kibana API via `curl` in cluster pod like 
`curl -k -i  -H "kbn-xsrf: true" -X GET "https://kibana:443/api/saved_objects/_find?type=dashboard&fields=id"`, 
I always got 
`<a href="https://oauth-openshift.apps.xxxxx.com/oauth/authorize?approval_prompt=force&client_id=system:serviceaccount:openshift-logging:kibana&redirect_uri=https://kibana/oauth/callback&response_type=code&scope=user:info user:check-access user:list-projects&state=x6f85:/api/saved_objects/_find%3Ftype=dashboard&fields=id">Found</a>`

and when I called with href url
`curl -k -i  -H "kbn-xsrf: true" -X GET "https://oauth-openshift.apps.xxxxx.com/oauth/authorize?approval_prompt=force&client_id=system:serviceaccount:openshift-logging:kibana&redirect_uri=https://kibana/oauth/callback..."`
I always got 
`{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"fx30f6:/api/saved_objects/_find?type=dashboard\u0026fields=id"}`

How to import kibana dashboard **from CLI** in k8s cluster?

**Comment by jcantrill** [comment]
This is an ad-hoc script that can be used to import visualizations from the CLI that were exported from the UI

**Comment by morningspace** [comment]
@jcantrill What the ad-hoc script do you mean? Are you saying that this scenario is not supported by OpenShift EFK? What we are trying to do is to install some pre-defined dashboards along w/ OpenShift EFK when our application is deployed and launched on OCP, so we need a way to import these dashboard definitions in background rather than asking customer to import from UI by themselves.

Meanwhile, it appears Kibana pod has a proxy container which implements OAuth, and right now we are accessing it on the same cluster from another pod, so that's in-cluster access. It looks it's unnecessary to go through OAuth flow in such a case for in-cluster access.

**Comment by lihongbj** [comment]
@jcantrill , could you please get a chance to reply @morningspace 's comments?
