### ISSUE TITLE
docker images are not updated anymore

### ISSUE THREAD

**Issue by chatziparaskewas** [openshift/origin-aggregated-logging#2220]
**Describe the bug**
A fix for the Log4Shell vulnerability has been applied, e.g. against the release-3.11 branch, however, on quay.io (and elsewhere) the latest 3.11 elasticsearch5 docker image does not contain the fix. Instead images are built every so many hours (multiple times a day), but in the end the same docker images are kept. I think the 3.11 docker images are the same since over a year.

**Environment**
- n/a

**Logs**
n/a

**Expected behavior**
Changes on the 3.11 branch are eventually in a reasonable timeframe reflected in the quay.io docker images.

**Actual behavior**
Changes on the 3.11 branch are not reflected in the quay.io docker images.

**To Reproduce**
1.  docker pull quay.io/openshift/origin-logging-elasticsearch5:v3.11.0
2.  docker run -it --rm --entrypoint=/bin/bash quay.io/openshift/origin-logging-elasticsearch5:v3.11.0
3. check /opt/app-root/src/run.sh for the fix "-Dlog4j2.formatMsgNoLookups=true" (which is missing)

**Additional context**
none

**Comment by BalazsGyarmati** [comment]
hi @chatziparaskewas 

(I'm not one of contributors, just noticed this as an OKD user)
As you can see there is a red X next to the commit: https://github.com/openshift/origin-aggregated-logging/commit/d1198209532263205954f730fe523ca117d29461
Which means some of the steps failed during the image build, which you can see here:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-origin-aggregated-logging-release-3.11-images/1471476743117213696

That's why the image doesn't contain the fixed code, because it doesn't build correctly.

**Comment by jcantrill** [comment]
@sosiouxme do you know if we are pushing or maintaining any "upstream" images for 3.11? My suspicion is most places we are only building product images for customers?
