### ISSUE TITLE
secure_forward connections to Logstash fail

### ISSUE THREAD

**Issue by elyscape** [openshift/origin-aggregated-logging#279]
I'm trying to set up Fluentd to forward logs to a Logstash using the `secure_forward` output, as described in [the aggregated logging documentation][docs]. From what I can tell, Fluentd's `secure_forward` output plugin has a hard requirement of a shared key, which it uses to perform a handshake immediately after connection. Unfortunately, as far as I can determine, there is no way to make Logstash perform this handshake. This results in Fluentd opening a connection, attempting to perform a handshake, and then dropping the connection after 15 seconds or so due to the lack of response.

The following is an excerpt from [the docs][docs]:

>If the external aggregator is Logstash, with Logstash 2.4 it can be configured to interpret messages from [Fluentd] and can be configured to use [SSL].

This implies that the author (which, as per openshift/openshift-docs#2969, appears to be @ewolinetz) has somehow managed to get this to work. Could this be expanded on or explained? I've been unable to get this to work on my own, and I imagine others would run into the same issue.

[docs]: https://docs.openshift.org/latest/install_config/aggregate_logging.html#fluentd-secure-forward
[Fluentd]: https://www.elastic.co/guide/en/logstash/current/plugins-codecs-fluent.html
[SSL]: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html#ssl_enable

**Comment by ewolinetz** [comment]
That is misleading... as you observed, a `shared_key` is required for the `secure_forward` plugin. Unfortunately there will need to be another Fluentd hop in there to be able to publish to Logstash if it is desired to do it 'securely'.

If instead of `secure_forward` you use the `forward` plugin to ship logs to Logstash, otherwise it appears that you would need to have another Fluentd that has a `secure_forward` source, and that would need to send to Logstash (however, it seems that it would still need to be done insecurely)...

I have opened an issue [1] to allow making `shared_key` optional for when we are using it as an output so that alternate aggregators can ingest our logs. Currently it does appear that `secure_forward` is limited to Fluentd -> Fluentd communication. I'll make an update to our docs to explain this limitation.

[1] https://github.com/tagomoris/fluent-plugin-secure-forward/issues/53

**Comment by elyscape** [comment]
@ewolinetz I did some research and it turns out that the `out_forward` plugin won't work for connecting to Logstash either. Logstash's `tcp` input assumes that you'll open a socket and then push a bunch of messages separated by newlines. Fluentd's `out_forward` plugin opens a socket and then sends MessagePack arrays with no delimiters between them. Additionally, due to the way Fluentd is configured here, there are often newlines at the end of the log message, which happens midway through the MessagePack object. This causes Logstash to chop the messages in the wrong location (or just assemble huge megamessages) which then fail parsing in the codec. Furthermore, there is no way to tell Fluentd to put a delimiter between messages and no way to tell Logstash not to look for delimiters. As such, there does not appear to be any way to make Fluentd talk to Logstash without some sort of middle-man (e.g. Kafka, RabbitMQ).

**Comment by elyscape** [comment]
As a fun aside, there's a Lumberjack/Beats input plugin for Fluentd which allows Logstash to talk to Fluentd, but I can't find anything going the other way.

**Comment by ewolinetz** [comment]
@elyscape out of curiosity, what about using Logstash's `udp` input?

**Comment by elyscape** [comment]
Fluentd's `out_forward` plugin only supports using UDP for heartbeats, unfortunately.

**Comment by richm** [comment]
Can we close this issue?  If not, what do we need to do from the openshift fluentd side?

**Comment by oskiebe** [comment]
Hi, as there was no update for quite some time: any progress in this regard meanwhile?

We're basically running into the same issue when trying to forward fluentd logs to Logstash over SSL/TLS, and adding a bogus fluentd hop just to compensate for a protocol deficiency doesn't really feel sensible.

**Comment by richm** [comment]
use the out_tcp plugin - see https://github.com/openshift/origin-aggregated-logging/blob/master/test/out_rawtcp.sh for a test which does this
