### ISSUE TITLE
deployed EFK error

### ISSUE THREAD

**Issue by wenskys** [openshift/origin-aggregated-logging#35]
Hello,
    when i deployed the openshift-EFK[1],that are some error for this,such as
![error](https://cloud.githubusercontent.com/assets/12937669/12010763/88d75400-acee-11e5-917d-e26e4d4a5bb6.png)
    thank you!
[1] https://docs.openshift.org/latest/install_config/aggregate_logging.html

**Comment by wenskys** [comment]
supplement ：Try to refresh security configuration but it failed due to org.elasticsearch.action.NoShardAvailableActionException。
the es is run at node。

**Comment by ewolinetz** [comment]
Hi @wenskys, that error is coming from the Searchguard plugin we are using for mutual TLS.  It may be attempting to load it's configurations before Elasticsearch has them written and available.  

Do you see that error repeating every one second, or is it just the one time?

**Comment by wenskys** [comment]
just the one time.when error,that the kibana have no data.
sometimes is good,but most time is error for EFK.

**Comment by ewolinetz** [comment]
This is something that we've seen before.  It is a non-issue; I believe it's due to the timing of the Searchguard plugin trying to read its configurations from Elasticsearch before the data is available and just not handling this gracefully.

A PR [1] to address this was merged upstream and will work to get this added to our image moving forward.

[1] https://github.com/floragunncom/search-guard/pull/66

**Comment by wenskys** [comment]
thank，i will try again。
