### ISSUE TITLE
[RFE] Allow running a consolidated ops/logs cluster as opposed to requiring a separate ops cluster

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin-aggregated-logging#61]
My suspicion is that, when using a "separate" ops cluster, the ops cluster is also capturing all of the user app data, which results in duplication of data.

Or is the back-end configured such that the ops kibana cluster is pulling the data for the app logs from the regular elasticsearch cluster?

**Comment by jcantrill** [comment]
@thoraxe Looks like this https://github.com/openshift/origin-aggregated-logging/pull/60 should answer your question. It provides the ability to control where copies of logs are going.  @ewolinetz @richm can you please confirm

**Comment by jcantrill** [comment]
@ewolinetz @richm  can you verify if https://github.com/openshift/origin-aggregated-logging/pull/60 answers @thoraxe  question?

**Comment by richm** [comment]
I don't understand the question.  https://github.com/openshift/origin-aggregated-logging/pull/60 gives you the ability to "fork" the data stream into two completely separate Elasticsearch instances - the "internal" one provided by OpenShift, which requires the tight searchguard/kubernetes/ssl/cert integration, and one that can be completely wide open (no access control, no ssl, no username/password).

**Comment by richm** [comment]
In addition, with https://github.com/openshift/origin-aggregated-logging/pull/60, the "external" destination is in no way accessible by the OpenShift Kibana container - Kibana doesn't know anything about it, and I doubt the auth proxy can be configured to allow access to it.

**Comment by ewolinetz** [comment]
@thoraxe when we have the separate ops cluster Fluentd will actually make decisions based on the source project of the data as to where it goes.  In fact we technically always send anything that would be considered an 'ops' log message to the [ES] ops host.  In cases where we aren't using an ops cluster we have set the ops host to be the same as the normal [ES] app host.

The ops kibana should only be connecting to the ops Elasticsearch, so you shouldn't be able to see any actual application data.  Which is probably misleading since we will pre-populate the indices of projects that you have available to you (which as a cluster-admin is everything), so you'll see the indices created within the ops kibana, however you should not ever see any data within the indices other than `.operations.*`.

Is this not the case in what you're seeing?

**Comment by thoraxe** [comment]
I have not actually logged into a non-ops cluster as a cluster-admin user and verified platform logs were aggregated there. If you are telling me that is what happens then I will gladly close.

**Comment by ewolinetz** [comment]
Yes, this is what you should see; when you do not use ENABLE_OPS_CLUSTER your platform and application logs will be available from the same Kibana.

**Comment by thoraxe** [comment]
Verified.
