### ISSUE TITLE
Access to deleted namespace logs

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#778]
Trying to open up the discussion on how to handle access to deleted namespace logs.  Currently, the visibility to logs is via Kibana.  We create an index-mapping to the namespaces that are visible to you from which you may see logs.  If you lose access or the namespace is deleted, we remove the mapping from your profile and thus the logs are stranded except for someone who has cluster admin rights.  Are there any thoughts is this is the proper way to deal with this usecase?

cc @openshift/sig-integration-services

**Comment by sosiouxme** [comment]
Has anyone asked for it to be otherwise? Who do they want accessing project logs after they're deleted?

(Losing access is different, right? Access can be restored as long as the project remains)

I'm sure it would be nice for cluster-admins to somehow enable access to log indexes that doesn't depend on OpenShift RBAC, but that seems like it would be complicated.

**Comment by richm** [comment]
The problem is that, if there are a lot of logs, and fluentd is slow to process them, there will be logs which refer to namespaces that may have already been deleted.  Or there may be other cases where the k8s meta plugin is unable to lookup the namespace to get the uuid.  We need to figure out what Elasticsearch index to write these logs to.

**Comment by jcantrill** [comment]
My question is not related to write but how do we make them available for viewing.  My suspicion is an admin would need to intervene and set up ES permissions in some way to allow users access to them.
